name: Test Happiness Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run Unit Tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t happiness-pipeline .

    - name: Run pipeline container
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
        docker run --env-file .env happiness-pipeline
